In [ ]:
import pandas as pd

In [3]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 100)

In [4]:
df=pd.read_csv("sales.csv",encoding="latin1")

In [21]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters by Universal,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [22]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,Florida,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Carpets,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,California,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,California,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection",243.160,2,0.0,72.9480

In [25]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [27]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [28]:
df.sample()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5207,5208,CA-2015-102015,9/12/2015,9/18/2015,Standard Class,TM-21010,Tamara Manning,Consumer,United States,Auburn,New York,13021,East,OFF-LA-10002043,Office Supplies,Labels,Avery 489,20.7,2,0.0,9.936

In [30]:
df.isnull().sum

<bound method DataFrame.sum of       Row ID  Order ID  Order Date  Ship Date  Ship Mode  Customer ID  \
0      False     False       False      False      False        False
1      False     False       False      False      False        False
2      False     False       False      False      False        False
3      False     False       False      False      False        False
4      False     False       False      False      False        False
...      ...       ...         ...        ...        ...          ...
9989   False     False       False      False      False        False
9990   False     False       False      False      False        False
9991   False     False       False      False      False        False
9992   False     False       False      False      False        False
9993   False     False       False      False      False        False

      Customer Name  Segment  Country   City  State  Postal Code  Region  \
0             False    False    False  False  False        False   False
1             False    False    False  False  False        False   False
2             False    False    False  False  False        False   False
3             False    False    False  False  False        False   False
4             False    False    False  False  False        False   False
...             ...      ...      ...    ...    ...          ...     ...
9989          False    False    False  False  False        False   False
9990          False    False    False  False  False        False   False
9991          False    False    False  False  False        False   False
9992          False    False    False  False  False        False   False
9993          False    False    False  False  False        False   False

      Product ID  Category  Sub-Category  Product Name  Sales  Quantity  \
0          False     False         False         False  False     False
1          False     False         False         False  False     False
2          False     False         False         False  False     False
3          False     False         False         False  False     False
4          False     False         False         False  False     False
...          ...       ...           ...           ...    ...       ...
9989       False     False         False         False  False     False
9990       False     False         False         False  False     False
9991       False     False         False         False  False     False
9992       False     False         False         False  False     False
9993       False     False         False         False  False     False

      Discount  Profit
0        False   False
1        False   False
2        False   False
3        False   False
4        False   False
...        ...     ...
9989     False   False
9990     False   False
9991     False   False
9992     False   False
9993     False   False

[9994 rows x 21 columns]>

In [31]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [32]:
df.shape

(9994, 21)

In [34]:
df["Sales"].sum()

np.float64(2297200.8603)

In [35]:
df["Profit"].sum()

np.float64(286397.0217)

In [36]:
df["Order ID"].nunique()

5009

In [38]:
df.groupby("Category")["Sales"].sum().sort_index(ascending=False)

Category
Technology         836154.0330
Office Supplies    719047.0320
Furniture          741999.7953
Name: Sales, dtype: float64

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [7]:
cat_sales = df.groupby("Category")["Sales"].sum().reset_index()
cat_sales = cat_sales.sort_values("Sales", ascending=False)

fig = px.bar(cat_sales, 
             x="Category", 
             y="Sales", 
             title="Sales by Category",
             color="Category")
fig.show()

In [13]:
reg_sales = df.groupby("Region")["Sales"].sum().reset_index()

fig = px.pie(reg_sales, 
             names="Region", 
             values="Sales", 
             title="Sales by Region")
fig.show()

In [15]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month Name"] = df["Order Date"].dt.strftime("%b")

print("Date columns added ✅")
df[["Order Date", "Year", "Month", "Month Name"]].head()

Date columns added ✅

  Order Date  Year  Month Month Name
0 2016-11-08  2016     11        Nov
1 2016-11-08  2016     11        Nov
2 2016-06-12  2016      6        Jun
3 2015-10-11  2015     10        Oct
4 2015-10-11  2015     10        Oct

In [16]:
monthly = df.groupby(["Year", "Month Name", "Month"])["Sales"].sum().reset_index()
monthly = monthly.sort_values(["Year", "Month"])

fig = px.line(monthly, 
              x="Month Name", 
              y="Sales", 
              color="Year",
              title="Monthly Sales Trend",
              markers=True)
fig.show()

In [17]:
Top_products=df.groupby("Product Name")["Sales"].sum().reset_index()
Top_products = Top_products.sort_values("Sales", ascending=False).head(10)

fig=px.bar( Top_products,
           x="Sales",
           y="Product Name",
           orientation="h",
           title="Top 10 Products By Sale")
fig.show()

In [18]:
profit_cat = df.groupby("Category")["Profit"].sum().reset_index()

fig = px.bar(profit_cat,
             x="Category",
             y="Profit",
             title="Profit by Category",
             color="Profit",
             color_continuous_scale="RdYlGn")
fig.show()

In [19]:
fig = px.scatter(df, 
                 x="Sales", 
                 y="Profit",
                 color="Category",
                 title="Sales vs Profit",
                 hover_data=["Product Name"])
fig.show()

In [22]:
top_customers=df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(5)
print(top_customers)

Customer Name
Sean Miller      25043.050
Tamara Chand     19052.218
Raymond Buch     15117.339
Tom Ashbrook     14595.620
Adrian Barton    14473.571
Name: Sales, dtype: float64

In [25]:
top_customers=df.groupby("Customer Name")["Sales"].sum().sort_values(ascending=False).head(5).reset_index()

fig=px.bar(top_customers,
           x="Customer Name",
           y="Sales",
           title="Top 5 Customers",
           color="Customer Name")
fig.show()

In [26]:
top_states=df.groupby("State")["Sales"].sum().sort_values(ascending=False).head(5).reset_index()

fig=px.bar(top_states,
           x="State",
           y="Sales",
           title="Top 5 States by Sales",
           color="State")
fig.show()

In [27]:
top_states_profit=df.groupby("State")["Profit"].sum().sort_values(ascending=False).head(5).reset_index()

fig=px.pie(top_states_profit,
           names="State",
           values="Profit",
           title="Top 5 States By Profit ")
fig.show()

In [29]:
top_subCategory=df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(5).reset_index()

fig=px.bar(top_subCategory,
           x="Sub-Category",
           y="Sales",
           title="Top 5 Sales By Sub-Category",
           color="Sub-Category")
fig.show()

In [31]:
top_subCategory_profit=df.groupby("Sub-Category")["Profit"].sum().sort_values(ascending=False).head(5).reset_index()

fig=px.bar(top_subCategory_profit,
           x="Sub-Category",
           y="Profit",
           title="Top 5 Profit By Sub-Category",
           color="Sub-Category")
fig.show()

In [33]:
top_profit_product=df.groupby("Product Name")["Profit"].sum().sort_values(ascending=False).head(10).reset_index()

fig=px.bar(top_profit_product,
           x="Product Name",
           y="Profit",
           title="Top 10 Products By Product",
           color="Product Name")
fig.show()

In [36]:
loss_products = df.groupby("Product Name")["Profit"].sum().sort_values().head(10).reset_index()

fig=px.bar(loss_products,
           x="Product Name",
           y="Profit",
           title="Top 10 Loss Making Products",
           color="Product Name")
fig.show()